projects:
  app:
    schemaPath: src/server/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
  prisma:
    schemaPath: src/server/generated/prisma.graphql
    includes: ["**/*.graphql"]
    extensions:
      prisma: prisma/prisma.yml